run_id: "SH_1112"
halfsib: "config/sample_3samples.csv"
phenotype: "phenotype/SH_phenotypes_1112_clean.tsv"
phenotype_names:
  [
    "PlantHeight",
    "StemLength",
    "PanicleNeckLength",
    "FlagLeafLength",
    "FlagLeafWidth",
    "PanicleNumber",
    "StemDiameterLength",
    "StemDiameterWidth",
    "StrawWeight",
    "GrainToStrawRatio",
    "YieldPerPlant",
    "KiloGrainWeight",
    "SeedSettingRate",
    "TotalGrainNumberPerPanicle",
    "FullGrainNumberPerPanicle",
    "TotalGrainNumber",
    "EmptyGrainNumber",
    "FullGrainNumber",
    "GrainShape",
    "GrainLength",
    "GrainWidth",
    "GrainArea",
    "Perimeter",
    "Roundness",
  ]

bfile:
  step1: "bfile/SH_f1_LDfilter"
  step2: "bfile/SH_f1"

software:
  - gcta
#  - emmax
# - regenie

pca: 5

plink:
  threads: 1

regenie:
  step1_threads: 1
  step2_threads: 1
  bsize: 20000

gcta:
  grm_threads: 1
  mlma_threads: 1

emmax:
  threads: 1
