run_id: "SH_1112"
halfsib: "config/sample_3samples.csv"
phenotype: "phenotype/SH_phenotypes_1112_clean.tsv"
phenotype_setting:
  PlantHeight: "dom"
  StemLength: "dom"
  PanicleNeckLength: "dom"
  FlagLeafLength: "dom"
  FlagLeafWidth: "add"
  PanicleNumber: "add"
  StemDiameterLength: "dom"
  StemDiameterWidth: "add"
  StrawWeight: "dom"
  GrainToStrawRatio: "dom"
  YieldPerPlant: "dom"
  KiloGrainWeight: "dom"
  SeedSettingRate: "dom"
  TotalGrainNumberPerPanicle: "dom"
  FullGrainNumberPerPanicle: "dom"
  TotalGrainNumber: "dom"
  EmptyGrainNumber: "dom"
  FullGrainNumber: "dom"
  GrainShape: "add"
  GrainLength: "add"
  GrainWidth: "add"
  GrainArea: "add"
  Perimeter: "add"
  Roundness: "add"

bfile:
  step1: "bfile/SH_f1_LDfilter"
  step2: "bfile/SH_f1"

software:
  - gcta
#  - emmax
# - regenie

pca: 5

plink:
  threads: 1

regenie:
  step1_threads: 1
  step2_threads: 1
  bsize: 20000

gcta:
  grm_threads: 1
  mlma_threads: 1

emmax:
  threads: 1
