run_id: "oh_no_1"
halfsib: "config/sample.csv"
phenotype: "phenotype/SH_phenotypes_mean_IDmapped.tsv"
phenotype_names: ["叶长", "株高"]

bfile:
  step1: "bfile/SH_f1_LDfilter"
  step2: "bfile/SH_f1"

software:
  # - gcta
  - emmax
# - regenie

pca: 5

plink:
  threads: 1

regenie:
  step1_threads: 4
  step2_threads: 4
  bsize: 20000

gcta:
  grm_threads: 4
  mlma_threads: 4
  chromosomes: 12

emmax:
  threads: 1
