run_id: "SH_1112"
halfsib: "config/sample_3samples.csv"
phenotype: "phenotype/SH_phenotypes_1112_clean.tsv"
phenotype_setting:
  PlantHeight: "dom"
  StemLength: "dom"
  PanicleNeckLength: "dom"
  FlagLeafLength: "dom"
  FlagLeafWidth: "add"
  PanicleNumber: "add"
  StemDiameterLength: "dom"
  StemDiameterWidth: "add"
  StrawWeight: "dom"
  GrainToStrawRatio: "dom"
  YieldPerPlant: "dom"
  KiloGrainWeight: "dom"
  SeedSettingRate: "dom"
  TotalGrainNumberPerPanicle: "dom"
  FullGrainNumberPerPanicle: "dom"
  TotalGrainNumber: "dom"
  EmptyGrainNumber: "dom"
  FullGrainNumber: "dom"
  GrainShape: "add"
  GrainLength: "add"
  GrainWidth: "add"
  GrainArea: "add"
  Perimeter: "add"
  Roundness: "add"

bfile:
  step1: "bfile/SH_f1_LDfilter"
  step2: "bfile/SH_f1"

pca: 5

plink:
  threads: 1

# per-phenotype transform (phenotypes not listed = no transform)
transform:
  PlantHeight: "iint"
  StemLength: "iint"
  PanicleNeckLength: "iint"
  FlagLeafLength: "iint"
  FlagLeafWidth: "iint"
  PanicleNumber: "iint"
  StemDiameterLength: "iint"
  StemDiameterWidth: "iint"
  StrawWeight: "iint"
  GrainToStrawRatio: "iint"
  YieldPerPlant: "iint"
  KiloGrainWeight: "ii"
  SeedSettingRate: "iint"
  TotalGrainNumberPerPanicle: "iint"
  FullGrainNumberPerPanicle: "iint"
  TotalGrainNumber: "iint"
  EmptyGrainNumber: "iint"
  FullGrainNumber: "iint"
  GrainShape: "iint"
  GrainLength: "iint"
  GrainWidth: "iint"
  GrainArea: "iint"
  Perimeter: "iint"
  Roundness: "iint"

gelex:
  grm_threads: 1
  assoc_threads: 1
